version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: exam_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      API_PORT: 8080
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/exam_platform?schema=public
      JWT_SECRET: change-me-for-production
      PROCTOR_API_TOKEN: change-me-proctor
      FRONTEND_PORT: 4173
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: ChangeMe123!
      UPLOADS_DIR: /app/apps/api/uploads
      ENABLE_AI_PROCTORING: "false"
      PROCTOR_SERVICE_URL: http://ai-proctor:8090
    depends_on:
      - postgres
    volumes:
      - uploads_data:/app/apps/api/uploads
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "4173:4173"
    depends_on:
      - api

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - api

volumes:
  postgres_data:
  uploads_data:
